//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/CurrencyService")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICurrencyService")]
    public interface ICurrencyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetMessage", ReplyAction="http://tempuri.org/ICurrencyService/GetMessageResponse")]
        string GetMessage(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetMessage", ReplyAction="http://tempuri.org/ICurrencyService/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetExchangeRate", ReplyAction="http://tempuri.org/ICurrencyService/GetExchangeRateResponse")]
        double GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetExchangeRate", ReplyAction="http://tempuri.org/ICurrencyService/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetHistoricalExchangeRate", ReplyAction="http://tempuri.org/ICurrencyService/GetHistoricalExchangeRateResponse")]
        double GetHistoricalExchangeRate(string currencyCode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetHistoricalExchangeRate", ReplyAction="http://tempuri.org/ICurrencyService/GetHistoricalExchangeRateResponse")]
        System.Threading.Tasks.Task<double> GetHistoricalExchangeRateAsync(string currencyCode, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/CreateAccount", ReplyAction="http://tempuri.org/ICurrencyService/CreateAccountResponse")]
        bool CreateAccount(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/CreateAccount", ReplyAction="http://tempuri.org/ICurrencyService/CreateAccountResponse")]
        System.Threading.Tasks.Task<bool> CreateAccountAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/TopUpAccount", ReplyAction="http://tempuri.org/ICurrencyService/TopUpAccountResponse")]
        bool TopUpAccount(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/TopUpAccount", ReplyAction="http://tempuri.org/ICurrencyService/TopUpAccountResponse")]
        System.Threading.Tasks.Task<bool> TopUpAccountAsync(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetBalance", ReplyAction="http://tempuri.org/ICurrencyService/GetBalanceResponse")]
        double GetBalance(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetBalance", ReplyAction="http://tempuri.org/ICurrencyService/GetBalanceResponse")]
        System.Threading.Tasks.Task<double> GetBalanceAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/Login", ReplyAction="http://tempuri.org/ICurrencyService/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/Login", ReplyAction="http://tempuri.org/ICurrencyService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/BuyCurrency", ReplyAction="http://tempuri.org/ICurrencyService/BuyCurrencyResponse")]
        bool BuyCurrency(string username, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/BuyCurrency", ReplyAction="http://tempuri.org/ICurrencyService/BuyCurrencyResponse")]
        System.Threading.Tasks.Task<bool> BuyCurrencyAsync(string username, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/SellCurrency", ReplyAction="http://tempuri.org/ICurrencyService/SellCurrencyResponse")]
        bool SellCurrency(string username, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/SellCurrency", ReplyAction="http://tempuri.org/ICurrencyService/SellCurrencyResponse")]
        System.Threading.Tasks.Task<bool> SellCurrencyAsync(string username, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetTransactionHistory", ReplyAction="http://tempuri.org/ICurrencyService/GetTransactionHistoryResponse")]
        CurrencyClient.ServiceReference1.Transaction[] GetTransactionHistory(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/GetTransactionHistory", ReplyAction="http://tempuri.org/ICurrencyService/GetTransactionHistoryResponse")]
        System.Threading.Tasks.Task<CurrencyClient.ServiceReference1.Transaction[]> GetTransactionHistoryAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyServiceChannel : CurrencyClient.ServiceReference1.ICurrencyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyServiceClient : System.ServiceModel.ClientBase<CurrencyClient.ServiceReference1.ICurrencyService>, CurrencyClient.ServiceReference1.ICurrencyService {
        
        public CurrencyServiceClient() {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage(string name) {
            return base.Channel.GetMessage(name);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string name) {
            return base.Channel.GetMessageAsync(name);
        }
        
        public double GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
        
        public double GetHistoricalExchangeRate(string currencyCode, string date) {
            return base.Channel.GetHistoricalExchangeRate(currencyCode, date);
        }
        
        public System.Threading.Tasks.Task<double> GetHistoricalExchangeRateAsync(string currencyCode, string date) {
            return base.Channel.GetHistoricalExchangeRateAsync(currencyCode, date);
        }
        
        public bool CreateAccount(string username, string password) {
            return base.Channel.CreateAccount(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAccountAsync(string username, string password) {
            return base.Channel.CreateAccountAsync(username, password);
        }
        
        public bool TopUpAccount(string username, double amount) {
            return base.Channel.TopUpAccount(username, amount);
        }
        
        public System.Threading.Tasks.Task<bool> TopUpAccountAsync(string username, double amount) {
            return base.Channel.TopUpAccountAsync(username, amount);
        }
        
        public double GetBalance(string username) {
            return base.Channel.GetBalance(username);
        }
        
        public System.Threading.Tasks.Task<double> GetBalanceAsync(string username) {
            return base.Channel.GetBalanceAsync(username);
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool BuyCurrency(string username, string currencyCode, double amount) {
            return base.Channel.BuyCurrency(username, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<bool> BuyCurrencyAsync(string username, string currencyCode, double amount) {
            return base.Channel.BuyCurrencyAsync(username, currencyCode, amount);
        }
        
        public bool SellCurrency(string username, string currencyCode, double amount) {
            return base.Channel.SellCurrency(username, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<bool> SellCurrencyAsync(string username, string currencyCode, double amount) {
            return base.Channel.SellCurrencyAsync(username, currencyCode, amount);
        }
        
        public CurrencyClient.ServiceReference1.Transaction[] GetTransactionHistory(string username) {
            return base.Channel.GetTransactionHistory(username);
        }
        
        public System.Threading.Tasks.Task<CurrencyClient.ServiceReference1.Transaction[]> GetTransactionHistoryAsync(string username) {
            return base.Channel.GetTransactionHistoryAsync(username);
        }
    }
}
